name: build

on:
  push:
    tags-ignore:
      - v*
    branches:
      - '*'
jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: setup-msbuild
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1
    - name: build for Windows
      if: matrix.os == 'windows-latest'
      run: |
        cmake -G "Visual Studio 16 2019" -A x64 -B "build"
        cd build
        msbuild github-actions-sample.sln /t:build /p:Configuration=Release
    - name: install gcc-10
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install gcc-10 g++-10 -y
      shell: bash
    - name: build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
      shell: bash
      env:
        CC: gcc-10
        CXX: g++-10
    - name: build for macOS
      if: matrix.os == 'macos-latest'
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
        